/*
 * Cashfree Payout APIs
 *
 * Cashfree's Payout APIs provide developers with a streamlined pathway to integrate advanced payout capabilities into their applications, platforms and websites.
 *
 * The version of the OpenAPI document: 2024-01-01
 * Contact: developers@cashfree.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = cashfree_payout.Client.OpenAPIDateConverter;

namespace cashfree_payout.Model
{
    /// <summary>
    /// It displays the payment instrument details of the beneficiary.
    /// </summary>
    [DataContract(Name = "Beneficiary_beneficiary_instrument_details")]
    public class BeneficiaryBeneficiaryInstrumentDetails : IEquatable<BeneficiaryBeneficiaryInstrumentDetails>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="BeneficiaryBeneficiaryInstrumentDetails" /> class.
        /// </summary>
        /// <param name="bankAccountNumber">It displays the bank account of the beneficiary..</param>
        /// <param name="bankIfsc">It displays the IFSC information of the beneficiary&#39;s bank account..</param>
        /// <param name="vpa">It displays the UPI VPA information of the beneficiary..</param>
        public BeneficiaryBeneficiaryInstrumentDetails(string bankAccountNumber = default(string), string bankIfsc = default(string), string vpa = default(string))
        {
            this.bank_account_number = bankAccountNumber;
            this.bank_ifsc = bankIfsc;
            this.vpa = vpa;
        }

        /// <summary>
        /// It displays the bank account of the beneficiary.
        /// </summary>
        /// <value>It displays the bank account of the beneficiary.</value>
        /// <example>00111122233</example>
        [DataMember(Name = "bank_account_number", EmitDefaultValue = false)]
        public string bank_account_number { get; set; }

        /// <summary>
        /// It displays the IFSC information of the beneficiary&#39;s bank account.
        /// </summary>
        /// <value>It displays the IFSC information of the beneficiary&#39;s bank account.</value>
        /// <example>HDFC0000001</example>
        [DataMember(Name = "bank_ifsc", EmitDefaultValue = false)]
        public string bank_ifsc { get; set; }

        /// <summary>
        /// It displays the UPI VPA information of the beneficiary.
        /// </summary>
        /// <value>It displays the UPI VPA information of the beneficiary.</value>
        /// <example>test@upi</example>
        [DataMember(Name = "vpa", EmitDefaultValue = false)]
        public string vpa { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class BeneficiaryBeneficiaryInstrumentDetails {\n");
            sb.Append("  bank_account_number: ").Append(bank_account_number).Append("\n");
            sb.Append("  bank_ifsc: ").Append(bank_ifsc).Append("\n");
            sb.Append("  vpa: ").Append(vpa).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as BeneficiaryBeneficiaryInstrumentDetails);
        }

        /// <summary>
        /// Returns true if BeneficiaryBeneficiaryInstrumentDetails instances are equal
        /// </summary>
        /// <param name="input">Instance of BeneficiaryBeneficiaryInstrumentDetails to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(BeneficiaryBeneficiaryInstrumentDetails input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.bank_account_number == input.bank_account_number ||
                    (this.bank_account_number != null &&
                    this.bank_account_number.Equals(input.bank_account_number))
                ) && 
                (
                    this.bank_ifsc == input.bank_ifsc ||
                    (this.bank_ifsc != null &&
                    this.bank_ifsc.Equals(input.bank_ifsc))
                ) && 
                (
                    this.vpa == input.vpa ||
                    (this.vpa != null &&
                    this.vpa.Equals(input.vpa))
                );
        }

        public static Boolean checkPresenceOfKey(string jsonStringbank_account_number) {
            dynamic deserializedJsonString = JsonConvert.DeserializeObject<dynamic>(jsonStringbank_account_number);
            if (deserializedJsonString.ContainsKey("bank_account_number")) {
                return true;
            }
            return false;
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.bank_account_number != null)
                {
                    hashCode = (hashCode * 59) + this.bank_account_number.GetHashCode();
                }
                if (this.bank_ifsc != null)
                {
                    hashCode = (hashCode * 59) + this.bank_ifsc.GetHashCode();
                }
                if (this.vpa != null)
                {
                    hashCode = (hashCode * 59) + this.vpa.GetHashCode();
                }
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
